---

- name: "Configure servers playbook" 
  hosts: web
  user: ansible-user
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  pre_tasks:
    - name: "Wait for target connection to become reachable/usable."
      wait_for:
        timeout: 60
  roles:
    - install-essentials
    - configure-nodejs
