---
- name: "Install NodeJs and npm"
  become: yes
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "Install pm2 process manager"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
