---
- name: Create app directory for backend
  become: yes
  file:
    path: /app
    state: directory
    recurse: yes
    owner: ansible-user
    group: wheel
- name: "Unarchive backend deployment files to server"
  become: true
  unarchive:
    src: ~/project/backend/backend-deployment.tar.gz
    dest: /app
    owner: ansible-user
    group: wheel
- name: "Run npm install"
  ansible.builtin.command: npm i
  args:
    chdir: /app
- name: Start app
  ansible.builtin.command: pm2 start npm --name "udapeople-backend" -- start
  args:
    chdir: /app
