Description: >
  UdaPeople backend stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String
  UbuntuAMI:
    Description: AMI Id for Ubuntu Server 18.04 LTS (eu-west-2)
    Type: AWS::EC2::Image::Id
    Default: ami-09a56048b08f94cdf

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroupss
    Properties:
      GroupName: !Sub UdaPeople-${ID}
      GroupDescription: Allow port 22 and port 3030.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3030
          ToPort: 3030
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity
      ImageId: !Ref UbuntuAMI
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}
