Description: >
  UdaPeople backend stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String
  UbuntuAMI:
    Description: AMI Id for Ubuntu Server 18.04 LTS (eu-west-2)
    Type: AWS::EC2::Image::Id
    Default: ami-09a56048b08f94cdf
  EC2PubKey:
    Description: EC2 instance public key
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub UdaPeople-${ID}
      GroupDescription: Allow port 22 and port 3030.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3030
          ToPort: 3030
          CidrIp: 0.0.0.0/0

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroupIds:
        - sg-0effec66e1ab81aff
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity
      ImageId: !Ref UbuntuAMI
      UserData:
        Fn::Base64: !Sub |
          #cloud-config
          cloud_final_modules:
          - [users-groups,always]
          users:
          - name: ansible-user
            groups: [ wheel ]
            sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
            shell: /bin/bash
            ssh-authorized-keys: 
            - ${EC2PubKey}
          - name: ubuntu
            groups: [ wheel ]
            sudo: [ "ALL=(ALL) NOPASSWD:ALL" ]
            shell: /bin/bash
            ssh-authorized-keys: 
            - ${EC2PubKey}

      Tags:
        - Key: Name
          Value: !Sub backend-${ID}
Outputs:
  BackendUrl:
    Description: Backend Public URL
    Value: !Sub
      - http://${BACKEND_URL}
      - { BACKEND_URL: !GetAtt EC2Instance.PublicDnsName }
    Export:
      Name: !Sub ${ID}-BACKEND-URL
