---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: Ubuntu-18.04
    image: docker.io/chrisk14/ubuntu-python3
    capabilities:
      - SYS_ADMIN
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
