---
- name: Update packages.
  become: yes
  apt:
    update_cache: yes

- name: Upgrade packages
  become: yes
  apt:
    upgrade: yes

- name: Autoremove dependencies
  become: yes
  apt:
    autoremove: yes

- name: Install build-essential tools
  become: yes
  apt:
    name: build-essential
