---
- name: Download PPA setup script from NodeSource
  get_url: 
    url: https://deb.nodesource.com/setup_12.x
    dest: ~/repo_setup.sh
    mode: 0744

- name: Run setup script
  become: yes
  ansible.builtin.command: ./repo_setup.sh
  args:
    chdir: ~

- name: Install NodeJs
  become: yes
  apt:
    name: nodejs

- name: Install PM2
  become: yes
  ansible.builtin.command: npm install pm2 -g