---
- name: Add PPA for Nodejs from NodeSource
  become: yes
  ansible.builtin.command: curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
  args:
    chdir: ~

- name: Install NodeJS
  become: yes
  apt:
    nodejs

- name: Install PM2
  become: yes
  ansible.builtin.command: npm install pm2 -g
